{% set name = "conda-souschef" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/conda-souschef/conda_souschef-3.0.1.tar.gz
  sha256: 0df9fa12d826ab349e8006e498c6067b3a5161cf5b860baf08601829cb1b200b

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3.0
    - setuptools-scm
    - wheel
  run:
    - python
    - ruamel.yaml >=0.15.3
    - ruamel.yaml.jinja2

test:
  source_files:
    - tests
  imports:
    - souschef
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/marcelotrevisani/souschef
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Project to handle conda recipes
  description: |
    Library to easily manipulate conda recipes.
  dev_url: https://github.com/marcelotrevisani/souschef
  doc_url: https://github.com/marcelotrevisani/souschef

extra:
  recipe-maintainers:
    - marcelotrevisani
